#
# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4

    working_directory: ~/repo

    environment:
      - REACT_APP_SERVER: https://bluecarbuncle-staging.herokuapp.com

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sh -x ./version.sh
      - run: yarn test
      - run: yarn build
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get install python-dev python-pip
            sudo pip install awscli
      - run: aws configure set default.s3.signature_version s3v4
      - run: aws configure set preview.cloudfront true
      - deploy:
          command: |
            aws s3 sync ~/repo/build s3://uskillity-frontend-staging/ --region eu-central-1 --acl public-read --delete;
            aws cloudfront create-invalidation --distribution-id E4HKCMC6NWB8 --paths /index.html;
