import React, { Component } from "react";

class Datenshutz extends Component {
  render() {
    return (
      <div>
        <h2>Data Protection and Privacy Policy</h2>
        <p>Last Update 01.05.2018</p>
        <p>
          When in this Privacy Policy the terms "u/skillity", "us" "our" or
          "ours" are mentioned, it is referred to the Nikolovska Becker UG/
          "u/skillity", who, according to the regulations of this Privacy
          Policy, is the "responsible body" and is holding the responsibility of
          your data.
        </p>
        <p>When we refer to learner</p>
        <p>When we refer to instructor</p>
        <p>YOUR DATA</p>
        <p>
          <strong>1. </strong>
          THE DATA WE STORE
        </p>
        <p>We store data related to your …</p>
        <p>
          • Account: During the registration process on our platform we ask you
          to fill in certain information like your name, your e-mail address and
          your birthday.
        </p>
        <p>
          • Profile: Profile picture, name and a personal description, which are
          supplied by yourself, are publicly displayed.
        </p>
        <p>
          • Communication with us and/or other users: The data which is
          generated through the communication with us or other users on the
          u/skillity platform, including the context of the information, is
          stored.
        </p>
        <p>
          • Ratings and Feedback: Ratings and feedback about other users and/or
          their services that they create.
        </p>
        <p>
          • Additional information: Data that is generated through the filling
          of forms, surveys, updates of your personal information, updates of
          your offerings, participation in special promotions or activity and
          postings in community forums.<strong />
        </p>
        <p>
          • Data usage: Information about your activities on the u/skillity
          platform including the opened pages, content you have accessed, your
          search questions, your bookings and all other activity being conducted
          on the platform.
        </p>
        <p>
          • Location data: When you use certain features on the platform we are
          granted the access to information about your location for instance
          your IP-Address, post code, or specific location data like the exact
          whereabouts of your mobile phone. If you do not want to release this
          information you can deactivate the location services on your phone.
        </p>
        <p>
          • Protocol data: When you use the u/skillity platform we automatically
          store protocol data, including when you use the platform without being
          registered or logged in. This includes the information about how you
          use the u/skillity platform (including any links for the usage of
          third parties), IP-Adresses, access times, information about used
          hard- and software, information about the used electronic devices,
          data related to specific device features (ex. crashes, type of
          browser) including the website that you searched, or interacted with
          before or after using the u/skillity platform.
        </p>
        <p>
          • Transaction data: We store information about your transactions on
          the u/skillity platform including the date and time, payments and
          other related transactions details.
        </p>
        <p>
          • Third party services: When you connect to u/skillity or register on
          the u/skillity platform through third party services (ex. Facebook,
          Instagram), and connect the u/skillity account with those services, we
          get access to information from them, for example your registration and
          profile information from the third party services. The way your data
          is transmitted to us depends on the terms and conditions of the third
          party services.
        </p>
        <p>
          • Google Analytics: We use functions of the web analytics service
          Google Analytics. Provider is Google Inc., 1600 Amphitheater Parkway
          Mountain View, CA 94043, USA. Google Analytics uses so-called
          "cookies". These are text files that are stored on your computer and
          that allow an analysis of the use of the website by you. The
          information generated by the cookie about your use of this website is
          usually transmitted to a Google server in the USA and stored there.
        </p>
        <p>
          • Payment Information: If you use our payment methods we do not save
          your payment information, that is done by our payment provider Stripe
          ( <a href="http://www.stripe.de">www.stripe.de</a>)
        </p>
        <p>2. HOW WE ARE USING THE DATA WE COLLECT</p>
        <p>
          The data that we store are used by u/skillity in the following way…
        </p>
        <p>
          • So we can enable the usage and access to the u/skillity platform.
        </p>
        <p>
          • So we can improve and optimise the platform through means of
          analysis and research.
        </p>
        <p>
          • So we can pass on important information to our payment provider ({" "}
          <a href="http://www.stripe.com">www.stripe.com</a>) which will make
          the buying and selling of tickets possible.
        </p>
        <p>
          • So we can send you important information, for instance changes to
          the T&amp;C etc.
        </p>
        <p>• So we can detect and prevent fraud and abuse</p>
        <p>• So we can comply with our legal obligations</p>
        <p>• So we can settle disputes with users</p>
        <p>
          • So we can enforce policies such as terms and conditions and similar
        </p>
        <p>
          • So we can to provide you with information, advertising or
          invitations to the offers or events published or provided on/by
          u/skillity
        </p>
        <p>DATA EXCHANGE BETWEEN USERS</p>
        <p>
          When booking as a learner, we will forward the following data to the
          course provider:
        </p>
        <p>• Your full name</p>
        <p>• Your ticket number</p>
        <p>• Your profile picture</p>
        <p>
          - other and/or necessary profile information, that you have agreed to
          disclose.
        </p>
        <p>
          When booking as a instructor, we will forward the following data to
          the learner:
        </p>
        <p>• Your full name</p>
        <p>• Your profile picture</p>
        <p>
          • other and/or necessary profile information, that you have agreed to
          disclose
        </p>
        <p>
          • In the case of automatic billing, necessary data, such as invoice
          number and full address will be acquired
        </p>
        <p>• Address of the location where the course takes place</p>
        <p>PUBLICLY ACCESSIBLE DATA</p>
        <p>
          On u/skillity, data will be published in such a way that they are
          accessible to the general public. These data includes, for example:
        </p>
        <p>
          • Areas of your public profile page such as your first name, your
          personal descriptions and the courses you have given or will give, the
          courses you have attended or will attend, reviews of other users about
          you or your courses.
        </p>
        <p>
          • Advertisement pages: They include information on availability, the
          instructor's public profile picture, aggregated data (such as page
          views in a given period of time) and any other information that the
          instructor has approved of.
        </p>
        <p>
          • After taking a course, learners and instructors can give ratings and
          feedback, which will also be publicly available.
        </p>
        <p>
          • If you submit content in a public forum or in a social media post or
          use a similar feature on the u/skillity platform, this content will be
          visible to all.
        </p>
        <p>
          • Data you share with u/skillity for everyone can be indexed through
          third-party search engines. We have no influence on the practices of
          search engines.
        </p>
        <p>Security and compliance</p>
        <p>
          u/skillity must disclose your information to courts, law enforcement
          and other government agencies or to authorised third parties if
          required to do so by law or if disclosure is required from an
          objective point of view for the following purposes:
        </p>
        <p>
          • to respond to claims brought against u/skillty in accordance with
          the requirements of a dispute
        </p>
        <p>
          • in response to verified inquiries relating to a criminal
          investigation or alleged unlawful act or other act that may expose us,
          you or other users to legal liability.
        </p>
        <p>
          • to enforce and apply our terms and conditions or other agreements
          with Members.
        </p>
        <p>
          • for fraud detection and prevention, risk assessment, customer care,
          product development and troubleshooting.
        </p>
        <p>
          • to protect the rights, property or personal safety of u/skillity,
          our employees, other members or the public.
        </p>
        <p>
          In case of such data request, we will try to inform members about it,
          unless:
        </p>
        <p>
          • We are prohibited from informing members by the legal process
          itself, by a court order or by any applicable law.
        </p>
        <p>
          • We believe that a disclosure would be pointless or unsuccessful,
          create a risk of injury to the body or health of a person or group of
          people, or create the risk of fraud to the detriment of u/skillity or
          other members.
        </p>
        <p>Mergers, acquisitions or reorganisations</p>
        <p>
          If u/skillity performs or participates in any merger, acquisition,
          reorganisation, asset sale, bankruptcy or insolvency proceeding, we
          may sell, transfer or transfer our assets, including your information.
          In this case, we will notify you before your personal information is
          transferred and covered by another privacy policy.
        </p>
        <p>Link to accounts with third parties.</p>
        <p>
          You can link your u/skillity account to your social media account.
          Your contacts on these third party services are called friends. When
          you create this link,
        </p>
        <p>
          • some of the data you submit to us by linking your accounts may be
          published on your u/skillity account profile;
        </p>
        <p>
          • your activities on u/skillity could be shown on the third party
          website;
        </p>
        <p>
          • a link to this third-party social network can be added to your
          public u/skillity profile;
        </p>
        <p>
          • u/skillity users may be able to see the common friends you share
          with them or whose common friend you may be;
        </p>
        <p>
          • other u/skillity users may be able to see schools, hometowns, or
          other groups that you share with them as listed in your linked social
          network;
        </p>
        <p>
          • the data you provide to us by linking your accounts may be stored,
          processed and transmitted for purposes of fraud prevention and risk
          assessment;
        </p>
        <p>
          The publication and display of data you submit to u/skillity through
          this link is based on your settings adjustments and therefrom the
          permissions you have given to u/skillity and the third party website
          through those adjustments.
        </p>
        <p>Data security:</p>
        <p>
          We operate to the highest security standards and constantly improve
          our data security. Since the Internet can't provide complete security,
          we try very hard to keep all data as secure as possible, but we can't
          guarantee overall security.
        </p>
        <p>Changes to the privacy policy:</p>
        <p>
          u/skillity reserves the right to change this Privacy Policy at any
          time in accordance with this provision. The amended privacy policy
          will be published on u/skillity. The most recent modification date
          will be noted at the beginning of the privacy policy statement.
        </p>
        <p>
          <strong>
            <em>Rights of Users:</em>
          </strong>
          <strong>
            <em />
          </strong>
        </p>
        <p>
          <em>
            Users have the right to receive information about their personal
            data that has been stored about them free of charge upon request. In
            addition, users have the right to correct inaccurate data, revoke
            consent, block and delete their personal data, as far as no legal
            retention requirements are precluding. The contact details can be
            found in the I
          </em>
          <em>mprint</em>
          <em> (Impressum).</em>
        </p>
      </div>
    );
  }
}

export default Datenshutz;
